name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
      
    - name: Install dependencies
      run: npm i
      
    - name: Test
      run: npm run test:ci
